In [2]:
import pandas as pd

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [6]:
from sklearn.naive_bayes import MultinomialNB

In [7]:
from sklearn import metrics

In [22]:
data = pd.read_excel("naviebayes.xlsx",names=['Message','Label'])

In [23]:
data

Message Label
0                This is an amazing place   pos
1      I feel very good about these beers   pos
2                    This is my best work   pos
3                    What an awesome view   pos
4           I do not like this restaurant   neg
5                I am tired of this stuff   neg
6                  I can’t deal with this   neg
7                    He is my sworn enemy   neg
8                     My boss is horrible   neg
9                This is an awesome place   pos
10  I do not like the taste of this juice   neg
11                        I love to dance   pos
12      I am sick and tired of this place   neg
13                   What a great holiday   pos
14         That is a bad locality to stay   neg
15         We will have good fun tomorrow   pos
16       I went to my enemy’s house today   neg

In [24]:
data.shape

(17, 2)

In [25]:
data['boolean_emotion'] = data.Label.map({'pos':1,'neg':0})
data

Message Label  boolean_emotion
0                This is an amazing place   pos                1
1      I feel very good about these beers   pos                1
2                    This is my best work   pos                1
3                    What an awesome view   pos                1
4           I do not like this restaurant   neg                0
5                I am tired of this stuff   neg                0
6                  I can’t deal with this   neg                0
7                    He is my sworn enemy   neg                0
8                     My boss is horrible   neg                0
9                This is an awesome place   pos                1
10  I do not like the taste of this juice   neg                0
11                        I love to dance   pos                1
12      I am sick and tired of this place   neg                0
13                   What a great holiday   pos                1
14         That is a bad locality to stay   neg                0
15         We will have good fun tomorrow   pos                1
16       I went to my enemy’s house today   neg                0

In [26]:
v = TfidfVectorizer()

In [27]:
vdata = v.fit_transform(data.Message)

In [31]:
vdata

<17x55 sparse matrix of type '<class 'numpy.float64'>'
	with 87 stored elements in Compressed Sparse Row format>

In [39]:
set((" ".join(data.Message)).split(" ")).difference(set(v.get_feature_names_out())) #it has ignored words with sus characters and pronouns

{'He', 'I', 'My', 'That', 'This', 'We', 'What', 'a', 'can’t', 'enemy’s'}

In [40]:
df = pd.DataFrame(vdata.toarray(),columns=v.get_feature_names_out())

In [42]:
df

about        am   amazing        an       and   awesome       bad  \
0   0.000000  0.000000  0.589549  0.461737  0.000000  0.000000  0.000000   
1   0.416578  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
3   0.000000  0.000000  0.000000  0.442107  0.000000  0.492899  0.000000   
4   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
5   0.000000  0.472250  0.000000  0.000000  0.000000  0.000000  0.000000   
6   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
7   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
9   0.000000  0.000000  0.000000  0.482067  0.000000  0.537449  0.000000   
10  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
11  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
12  0.000000  0.389249  0.000000  0.000000  0.445783  0.000000  0.000000   
13  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
14  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.447963   
15  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
16  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

       beers      best      boss  ...     today  tomorrow      very      view  \
0   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
1   0.416578  0.000000  0.000000  ...  0.000000  0.000000  0.416578  0.000000   
2   0.000000  0.562609  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
3   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.564485   
4   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
5   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
6   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
7   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
8   0.000000  0.000000  0.589376  ...  0.000000  0.000000  0.000000  0.000000   
9   0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
10  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
11  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
12  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
13  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
14  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
15  0.000000  0.000000  0.000000  ...  0.000000  0.416578  0.000000  0.000000   
16  0.000000  0.000000  0.000000  ...  0.452456  0.000000  0.000000  0.000000   

          we      went      what      will     with      work  
0   0.000000  0.000000  0.000000  0.000000  0.00000  0.000000  
1   0.000000  0.000000  0.000000  0.000000  0.00000  0.000000  
2   0.000000  0.000000  0.000000  0.000000  0.00000  0.562609  
3   0.000000  0.000000  0.492899  0.000000  0.00000  0.000000  
4   0.000000  0.000000  0.000000  0.000000  0.00000  0.000000  
5   0.000000  0.000000  0.000000  0.000000  0.00000  0.000000  
6   0.000000  0.000000  0.000000  0.000000  0.55212  0.000000  
7   0.000000  0.000000  0.000000  0.000000  0.00000  0.000000  
8   0.000000  0.000000  0.000000  0.000000  0.00000  0.000000  
9   0.000000  0.000000  0.000000  0.000000  0.00000  0.000000  
10  0.000000  0.000000  0.000000  0.000000  0.00000  0.000000  
11  0.000000  0.000000  0.000000  0.000000  0.00000  0.000000  
12  0.000000  0.000000  0.000000  0.000000  0.00000  0.000000  
13  0.000000  0.000000  0.525361  0.000000  0.00000  0.000000  
14  0.000000  0.000000  0.000000  0.000000  0.00000  0.000000  
15  0.416578  0.000000  0.000000  0.416578  0.00000  0.000000  
16  0.000000  0.452456  0.000000  0.000000  0.00000  0.000000  

[17 rows x 55 columns]

In [44]:
# the above data just gives importance of each word in the document

In [45]:
xtrain,xtest,ytrain,ytest = train_test_split(vdata,data.boolean_emotion,test_size=0.3,random_state=2)

In [54]:
ytrain #index and emotion

1     1
10    0
7     0
14    0
2     1
11    1
6     0
16    0
13    1
15    1
8     0
Name: boolean_emotion, dtype: int64

In [55]:
ytest

12    0
4     0
5     0
0     1
9     1
3     1
Name: boolean_emotion, dtype: int64

In [50]:
ytest.shape

(6,)

In [60]:
clf = MultinomialNB().fit(xtrain,ytrain)

In [61]:
pred = clf.predict(xtest)

In [62]:
pred

array([0, 0, 0, 0, 0, 1], dtype=int64)

In [63]:
ytest

12    0
4     0
5     0
0     1
9     1
3     1
Name: boolean_emotion, dtype: int64

In [64]:
metrics.accuracy_score(ytest,pred)

0.6666666666666666

In [65]:
metrics.confusion_matrix(ytest,pred)

array([[3, 0],
       [2, 1]], dtype=int64)

In [67]:
print(metrics.classification_report(ytest,pred))

              precision    recall  f1-score   support

           0       0.60      1.00      0.75         3
           1       1.00      0.33      0.50         3

    accuracy                           0.67         6
   macro avg       0.80      0.67      0.62         6
weighted avg       0.80      0.67      0.62         6



In [69]:
metrics.precision_score(ytest,pred)

1.0

In [70]:
metrics.recall_score(ytest,pred)

0.3333333333333333

In [71]:
realtime = TfidfVectorizer()

In [77]:
realdata = v.transform(["i am angry"])

In [78]:
realdata

<1x55 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [79]:
clf.predict(realdata)

array([0], dtype=int64)

In [138]:
#:>> it showed up as neagtive